services:
  napcat:
    environment:
      - ACCOUNT=${ACCOUNT}
      - WS_ENABLE=true
    container_name: napcat
    networks:
      - onebotnet
    ports:
      - 6099:6099
    restart: on-failure:3
    image: mlikiowa/napcat-docker:latest
    volumes:
      - nc-data:/root/.config/QQ
      - nc-config:/usr/src/app/napcat/config
volumes:
  nc-data:
  nc-config:

networks:
  onebotnet:
    external: true
